# O-RAN-SC
#
# Copyright (C) 2019 AT&T Intellectual Property and Nokia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#   This source code is part of the near-RT RIC (RAN Intelligent Controller)
#   platform project (RICP).
#


# Dockerfile to verify, build and publish MDCLOG packages
# Inherits C toolchain from buildpack-deps:stretch
# Adds required build tools

FROM nexus3.o-ran-sc.org:10004/o-ran-sc/bldr-ubuntu18-c-go:8-u18.04

RUN apt-get update && apt-get -q -y install \
  libjsoncpp-dev \
  rpm \
  devscripts \
  debhelper \
  gawk


RUN mkdir -p /tmp/build
COPY . /tmp/build
WORKDIR /tmp/build

# Compile and run unit tests:
RUN ./autogen.sh && \
    ./configure && \
    make all && \
    make test

# Build packages:
RUN make clean && \
    make distclean && \
    ./configure --with-rpm-dir=/tmp/pkgs && \
    make rpm-pkg && \
    make clean && \
    make distclean && \
    ./configure --with-deb-dir=/tmp/pkgs && \
    make deb-pkg

RUN cp /tmp/build/docker_test/publish.sh /bin
ENTRYPOINT ["/bin/publish.sh"]
